name: flutterzuela
description: Presentation about Venezuela made entirely on Flutter Web

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # mobile_flutter_merchant:
  #   path: c:\Users\tpolanski\Documents\GitHub\mobile_flutter_merchant\
  flutter_localizations:
    sdk: flutter
#  animation_cheat_page:
#    git:
#      url: git://github.com/tomaszpolanski/flutter-animations.git
#      ref: master

  cupertino_icons: ^0.1.0
  flutter_sidekick: ^0.1.3
  google_fonts: ^1.1.0
  http: ^0.12.2
  mockito: ^4.1.1
  process_run: ^0.10.1
  qr_flutter: ^3.0.1
  rxdart: ^0.24.1
  presentation: ^0.0.11
  url_launcher: ^5.4.1
  fake_async: 1.1.0-nullsafety
  universal_html: ^1.2.3
  photo_view: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.9.4
  fast_flutter_driver: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/venezuelans/
    - assets/venezuela/
    - assets/food/
    - assets/music/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Monoserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Monoserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Monoserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Monoserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Monoserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Monoserrat/Montserrat-Black.ttf
          weight: 900

    - family: Floks
      fonts:
        - asset: fonts/folks.ttf
          weight: 400

    - family: AnonymousPro
      fonts:
        - asset: fonts/AnonymouPro/AnonymousPro-Regular.ttf
          weight: 400
        - asset: fonts/AnonymouPro/AnonymousPro-Bold.ttf
          weight: 700