// ignore_for_file: directives_ordering
/// This file is autogenerated and should not be committed to source control

import '../big_app_test.dart' as big_app;

void main(List<String> args) {
  big_app.main(args);
}
